### ISSUE TITLE
Question: How long does it take for the update to reach packagist?

### ISSUE THREAD

**Issue by FBnil** [hmazter/laravel-schedule-list#16]
Just upgraded Laravel to 5.6
When I do a `composer require hmazter/laravel-schedule-list` I still get the old `composer.json` which gives the duplicate require of `dragonmantank/cron-expression` and `mtdowling/cron-expression`.

__Workaround:__
Replace the old content of `./vendor/hmazter/laravel-schedule-list/composer.json` with the new version in Git.
Also had to do iffy stuff to `./vendor/composer/installed.json` (remove the mtdowling/cron-expression entry)

__Real Workaround__:
Stay at Laravel 5.5
Wait until packagist updates to the newer version of laravel-schedule-list by checking that the Requires is from dragonmantank on this page:
https://packagist.org/packages/hmazter/laravel-schedule-list

__Possible action for hmazter__:
poke packagist? Need to read up on how that works.

**Comment by hmazter** [comment]
Hi

I haven't done a tag with that update yet since it is breaking backward compatibility, I need to tag v1.0.0 and before I do that I want to be done with #10.
I really hope I will get that done and tagged this week.

But if you want to use the latest version now you can always use `dev-master`.

```
composer require hmazter/laravel-schedule-list dev-master
```

Or you can use the tagged version and ignore the warnings for now. Everything should work, it's just a warning.

**Comment by FBnil** [comment]
No hurry, will run my Production on 5.5 until it can be migrated cleanly. Meanwhile, on my Development I'll checkout dev-master... Thanks for the effort @hmazter !
